In [108]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, RidgeCV, LassoCV, ElasticNetCV
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [2]:
df = pd.read_csv('../../Python for ML/08-Linear-Regression-Models/Advertising.csv')

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales', axis=1)

In [5]:
y = df['sales']

In [9]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [10]:
poly_features = polynomial_converter.fit_transform(X, y)

In [11]:
X.shape

(200, 3)

In [15]:
poly_features.shape

(200, 19)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=42)

In [20]:
X_train.shape

(140, 19)

In [22]:
scaler = StandardScaler()

In [23]:
scaler.fit(X_train)

StandardScaler()

In [26]:
X_train = scaler.transform(X_train)

In [27]:
X_test = scaler.transform(X_test)

In [28]:
X_train[0]

array([ 1.53003874, -0.8862929 , -1.16598019,  1.93705409, -0.22476356,
       -0.62651363, -0.90793157, -0.850692  , -0.81317305,  2.23096225,
        0.10749852, -0.35876444, -0.61820397, -0.60530328, -0.5751799 ,
       -0.81381745, -0.72447935, -0.64260728, -0.56741817])

In [29]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [32]:
ridge_model = Ridge(alpha=10)

In [33]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [34]:
test_predictions = ridge_model.predict(X_test)

In [35]:
test_predictions

array([16.62365354, 22.55866022, 20.96934981,  8.89161689, 24.09520123,
       12.47573851, 22.56502913,  8.61141517, 12.24214571, 15.00455225,
        8.82689506,  8.34808131, 12.09259398,  7.98423851, 10.25180234,
       11.95815057,  8.13437485, 15.95398183, 10.54942097, 18.62868744,
       19.9602247 , 12.4930582 , 10.45790132, 22.25720133,  8.94342403,
        7.92328035, 22.15621263, 12.04106425,  9.96987513,  7.94487395,
       11.65113047, 10.21212112, 23.3568017 ,  9.76824054, 15.88092304,
       20.64424742, 11.65266419, 20.5155286 , 11.25707804,  7.14917982,
       10.37068337, 12.31211621,  9.76568103,  9.13653789, 12.06192462,
        7.58522516,  9.92379751, 14.04602481,  9.82796978, 11.30495831,
       14.00400002, 11.71603724,  9.42979516,  8.78951143,  8.42818979,
       10.51761284,  9.96342573, 26.24631912,  8.09416369, 11.76362962])

In [38]:
MAE = mean_absolute_error(y_test, test_predictions)

In [40]:
MAE

0.6296591346758614

In [41]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [42]:
RMSE

np.float64(0.8916327541710883)

In [59]:
ride_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [60]:
ride_cv_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [61]:
ride_cv_model.alpha_

np.float64(0.1)

In [57]:
from sklearn.metrics import get_scorer_names

In [62]:
get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'd2_absolute_error_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_max_error',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'neg_root_mean_squared_log_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 're

In [63]:
test_predictions = ride_cv_model.predict(X_test)

In [64]:
MAE = mean_absolute_error(y_test, test_predictions)

In [65]:
MAE

0.46671241134224756

In [66]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [67]:
RMSE

np.float64(0.5945136672015398)

In [68]:
ride_cv_model.coef_

array([ 5.90523815,  0.46316396,  0.68028713, -6.17743395,  3.73671928,
       -1.40708382,  0.00624704,  0.11128917, -0.2617823 ,  2.17135744,
       -0.51480159,  0.70587211,  0.60311504, -0.53271216,  0.5716495 ,
       -0.34685826,  0.36744388, -0.03938079, -0.12192939])

LASSO - Least Absolute Shrinkage and Selection Operator

In [101]:
lasso_cv_model = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=1000000)

In [102]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, max_iter=1000000)

In [103]:
lasso_cv_model.alpha_

np.float64(0.004924531806474871)

In [104]:
test_predictions = lasso_cv_model.predict(X_test)

In [105]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.5123045552899822

In [106]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

np.float64(0.630804304917288)

In [107]:
lasso_cv_model.coef_

array([ 5.15048089,  0.4274257 ,  0.29684446, -4.53337994,  3.38937185,
       -0.4288993 ,  0.        ,  0.        ,  0.        ,  1.17891049,
       -0.        ,  0.        ,  0.16706037, -0.        ,  0.        ,
        0.        ,  0.11083672,  0.        ,  0.06155549])

In [94]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)

In [95]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [96]:
lasso_cv_model.alpha_

np.float64(0.4924531806474871)

In [97]:
test_predictions = lasso_cv_model.predict(X_test)

In [98]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.681145634283798

In [99]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

np.float64(1.0349127365478725)

In [109]:
lasso_cv_model.coef_

array([ 5.15048089,  0.4274257 ,  0.29684446, -4.53337994,  3.38937185,
       -0.4288993 ,  0.        ,  0.        ,  0.        ,  1.17891049,
       -0.        ,  0.        ,  0.16706037, -0.        ,  0.        ,
        0.        ,  0.11083672,  0.        ,  0.06155549])

In [110]:
elastic_model = ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0], eps=0.001, n_alphas=100, max_iter=1000000)

In [111]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0], max_iter=1000000)

In [112]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0]

In [113]:
elastic_model.l1_ratio_

np.float64(1.0)

In [114]:
elastic_model.alpha_

np.float64(0.004924531806474871)

In [115]:
lasso_cv_model.alpha_

np.float64(0.004924531806474871)

In [116]:
test_predictions = elastic_model.predict(X_test)

In [117]:
MAE = mean_absolute_error(y_test, test_predictions)
MAE

0.5123045552899822

In [118]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))
RMSE

np.float64(0.630804304917288)